track = reaper.GetTrack(0,0)
r = math.random(250)
g= math.random(250)
b=math.random(250)
offset = math.random(4)
color = reaper.ColorToNative(r + offset,g - offset,b + offset)
reaper.SetTrackColor(track, color)
track = reaper.GetTrack(0,1)
r = math.random(250)
g= math.random(250)
b=math.random(250)
offset = math.random(4)
color = reaper.ColorToNative(r + offset,g - offset,b + offset)
reaper.SetTrackColor(track, color)
track = reaper.GetTrack(0,2)
r = math.random(250)
g= math.random(250)
b=math.random(250)
offset = math.random(4)
color = reaper.ColorToNative(r + offset,g - offset,b + offset)
reaper.SetTrackColor(track, color)
track = reaper.GetTrack(0,3)
r = math.random(250)
g= math.random(250)
b=math.random(250)
offset = math.random(4)
color = reaper.ColorToNative(r + offset,g - offset,b + offset)
reaper.SetTrackColor(track, color)
reaper.ShowConsoleMsg("hey")
